# (PART) Part 1: Getting ready for submission {-}

# The reasons for publishing your work {- #part1}

Я предполагаю, что все вы захотите опубликовать работы из своих диссертаций, но стоит пройтись по пунктам, почему публикация так важна.

- Если ваша работа не опубликована, значит, она не будет использована. Без использования все вложенные вами силы пропадут.
- Ваша опубликованная работа станет основой для будущих студентов и ученых, которые будут работать в вашей области. Вполне возможно, что это будет в другой стране или на другом континенте.
- Ваша работа, скорее всего, была оплачена налогоплательщиками страны, в которой вы учились. Публикация этой работы - это способ вернуть ценность того, что вы нашли. Если работа опубликована в открытом доступе, общественность также может ознакомиться с ней самостоятельно.  
- Другие организации, финансирующие вашу диссертационную работу, могут сделать публикацию обязательным условием для получения финансирования.
- Есть надежда, что публикация вашей работы сделает ее более доступной для научного сообщества.
- Опубликовав свою работу, вы обнаружите, что и вы, и ваша работа стали известны международному сообществу, которое вполне может пригласить вас к дальнейшему участию в научном процессе [@marks2013misuse].
- Как в науке, так и за ее пределами опубликованные рецензируемые работы рассматриваются как важное достижение в дополнение к написанию диссертации.
- Работа, которую вы уже проделали над своей диссертацией (особенно если вы следовали советам этой книги!), означает, что вы близки к тому, чтобы подготовить главы, которые можно будет представить в качестве публикаций. 
- Ваш консультант и коллеги по лаборатории, которые помогали вам в работе над диссертацией, могут зависеть от ваших публикаций. 
- Увидев свою работу опубликованной, вы получите огромное удовлетворение. Утверждается, что это зависит от того, кто вы и откуда [@husemann2017publicationism]. 
- Удовольствие от того, что кто-то скажет, как приятно или вдохновляюще читать вашу работу, конечно, не будет таким частым, как если бы вам удалось опубликовать роман или газетную колонку. Но когда это произойдет, на вашем лице появится улыбка.

Это далеко не полный список, но я надеюсь, что он даст вам некоторое представление о важности публикации ваших результатов. В противовес этому утверждению, пожалуйста, имейте в виду, что есть исследования, которые говорят о том, что наука, основанная на публикации, не является здоровой, и что нам нужен новый способ мотивации науки [например, @stergiou2014impact]. Действительно, было высказано предположение, что менталитет «публикуйся или погибнешь» в академической среде привел к сохранению (и даже ухудшению) плохого экспериментального дизайна и, следовательно, к более высоким ложноположительным результатам в поведенческих науках [@smaldino2016natural]. Мы вернемся к этому позже в [части 4] (#badscience). Однако прежде чем присоединиться к дебатам о будущем, я бы утверждал, что вам необходимо предоставить свои полномочия в настоящем.

Учитывая, что вы читаете эту книгу, я предположу, что вы планируете опубликовать свои работы. Однако все же есть некоторые основы, которые, на мой взгляд, стоит рассмотреть в этой первой части книги:

- [Для чего нужен журнал?] (whatjournalfor.html)
- [Что можно публиковать?](whattowrite.html)
- [Что такое рецензирование](peerreview.html)
- [Что такое импакт-фактор журнала?](impactfactor.html)
- [Почему важны цитаты?](citations.html)


